### ISSUE TITLE
Create a master credits table

### ISSUE THREAD

**Issue by R0gue-one** [devansh-srv/Carbon-Credit#8]
currently there is a purchased_credit table which has credits not avail for sale, and Table:credits that are "for sale". 
If possible create a master table of all credits that has credit ID , name, creator, owner (if you want to add anything more than this then is okay) 

![image](https://github.com/user-attachments/assets/22a912ab-3f2c-4ff1-8c9b-ef2a6bd6db17)

This is to help us retrieve credits for admin as well as buyers. 
If you have any questions just let me know.

**Comment by devansh-srv** [comment]
will not be required
